<?php

use Illuminate\Database\Seeder;

class ConversationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('conversations')->delete();
        
        \DB::table('conversations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Repellendus sint beatae enim ut et.',
                'description' => 'Voluptas fugit dolor quo esse consequatur et. Blanditiis quia tempora blanditiis quia error. Qui porro laboriosam et vel deserunt nesciunt ex.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 1,
                'owner_type' => 'Project',
                'user_id' => 4,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Similique deserunt eos vel architecto et odio.',
                'description' => 'Consequuntur error odit sed fugiat. Quos neque explicabo recusandae sit velit blanditiis. Occaecati ex eaque debitis et.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 5,
                'owner_type' => 'Project',
                'user_id' => 5,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Quas earum qui quia magnam autem.',
                'description' => 'Sint assumenda commodi eos unde. Rerum fuga eos facere et. Non non molestiae veritatis optio voluptatum quibusdam vel blanditiis. Est magnam quo sit.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 10,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Impedit commodi quasi ducimus aut.',
                'description' => 'Doloremque et odit et nisi eveniet. Quod recusandae nihil culpa ducimus similique. Laboriosam maiores natus qui qui repudiandae nostrum.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 1,
                'owner_type' => 'Project',
                'user_id' => 4,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Aut nemo dolor aliquam.',
                'description' => 'Voluptatem laboriosam facere consequatur quas quos nemo asperiores. Ullam unde ipsum qui. Quis quia voluptatem in qui commodi unde.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 6,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Cum laudantium commodi culpa corrupti quo architecto.',
                'description' => 'Voluptatem aperiam repellat ipsa ut occaecati. Voluptas corrupti illum consequuntur. Tempore dolor eligendi error autem in.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 2,
                'owner_type' => 'Project',
                'user_id' => 3,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Voluptatibus expedita quod dolore est.',
                'description' => 'Ab exercitationem facere aut ullam molestiae quaerat. Quam architecto aut dolorum officiis. Qui perspiciatis deleniti labore quisquam aliquid sit. Incidunt nihil facere blanditiis dolores tempore autem eaque.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 7,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Quo est pariatur ullam quia.',
                'description' => 'Eos explicabo est consequatur deleniti cumque. Quidem similique tempore sunt deleniti exercitationem distinctio. Et accusantium maxime nihil et illo odio. Aperiam iure quaerat delectus dolorum tempore ea exercitationem. Quia tempore quia iusto corporis ut',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 8,
                'owner_type' => 'Project',
                'user_id' => 3,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Molestiae earum placeat corporis autem nam.',
                'description' => 'Vel et velit omnis reprehenderit autem maiores architecto earum. Aperiam repellat ut maxime accusamus voluptatum odit.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 8,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Eum est quo perferendis neque nulla occaecati.',
                'description' => 'Doloremque natus vitae sed ratione nisi architecto consequatur. Et quae ipsum nostrum laudantium minus. Similique labore aut ad sunt.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 1,
                'owner_type' => 'Project',
                'user_id' => 2,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Et non ipsum maxime omnis non aliquid quo.',
                'description' => 'Vitae molestias vel dolor odit. Et accusamus doloremque vitae eum. Praesentium corrupti et similique excepturi iure pariatur. Vel ipsam blanditiis illo et id sed.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 10,
                'owner_type' => 'Project',
                'user_id' => 9,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Maxime laudantium sit nihil quis.',
                'description' => 'Perspiciatis quia aut delectus. Odit odio totam minus error voluptatem ducimus. Sed saepe sint rerum nisi iste unde inventore. Temporibus quasi magnam modi ad aut.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 8,
                'owner_type' => 'Project',
                'user_id' => 9,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Consequuntur sequi quia nam culpa occaecati saepe.',
                'description' => 'Exercitationem non blanditiis accusantium quo nostrum. Aliquam sed reprehenderit debitis placeat et.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 1,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Cum iure id quia et est vero inventore.',
                'description' => 'Ut facere eos tenetur eos. Aspernatur non rerum blanditiis laborum aut quidem itaque voluptatem. Ipsum accusantium aut quas est. Ratione veritatis expedita blanditiis consequatur debitis.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 2,
                'owner_type' => 'Project',
                'user_id' => 5,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Debitis aut quaerat autem debitis impedit explicabo odio.',
                'description' => 'Voluptatem esse ut facilis est libero reprehenderit. Et atque voluptate eos voluptates asperiores tempore aliquam ipsam. Ut repellendus cupiditate quam assumenda asperiores id sapiente voluptatibus.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 7,
                'owner_type' => 'Project',
                'user_id' => 9,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Eum hic est voluptatibus aut ipsum nam occaecati.',
                'description' => 'Repellat voluptatem voluptates nemo atque voluptas. Perferendis corporis consequatur quisquam voluptates quia rerum labore. Quibusdam fugit asperiores quis.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 2,
                'owner_type' => 'Project',
                'user_id' => 8,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Quasi voluptatem aut fugit dolor accusantium vel.',
                'description' => 'Quam dolores asperiores molestiae similique. Vel ab blanditiis totam qui accusantium. Pariatur corrupti beatae quia.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 2,
                'owner_type' => 'Project',
                'user_id' => 7,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Nisi sequi nostrum vitae dolorum quis voluptatem quae harum.',
                'description' => 'Similique provident porro rerum iure dolores. Impedit laudantium debitis at odio. Quas expedita voluptatem eum voluptatem aut.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 2,
                'owner_type' => 'Project',
                'user_id' => 2,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Cum odio ut aspernatur vel et.',
                'description' => 'Deserunt voluptas sit natus iure iure quasi tenetur aperiam. Et non repellat at voluptatem cumque. In sequi autem quo quis. Eos qui fugit asperiores sapiente consequatur facilis numquam. Sequi sit cum qui quis autem consequatur totam.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 7,
                'owner_type' => 'Project',
                'user_id' => 2,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Omnis minus nobis enim rerum.',
                'description' => 'Consequatur totam qui ut nihil. Saepe omnis molestiae eum veritatis enim nam animi. Neque officia maiores nobis nihil ad ut. Consequatur autem mollitia doloremque dolores praesentium. Incidunt fuga omnis magni error ea tempore neque.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 5,
                'owner_type' => 'Project',
                'user_id' => 3,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
        ));
        
        
    }
}
