<?php

use Illuminate\Database\Seeder;

class ConversationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('conversations')->delete();
        
        \DB::table('conversations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Ut at enim et est ea excepturi mollitia.',
                'description' => 'Eius occaecati vel illum eaque labore qui nemo. Cumque aspernatur praesentium laborum sed. Reprehenderit eveniet ex velit dolorem illum.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 4,
                'owner_type' => 'Project',
                'user_id' => 10,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Maiores blanditiis voluptas esse aliquam dolores voluptatem voluptate quisquam.',
                'description' => 'Sequi distinctio sit exercitationem tenetur. Qui tempore ratione minima suscipit. Quae dolore incidunt sit vero vitae totam sequi.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 6,
                'owner_type' => 'Project',
                'user_id' => 9,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Facere quas tempora rem.',
                'description' => 'Et quia voluptatibus dicta molestiae. Voluptatem ut inventore expedita aut cumque. Aut non magni sapiente velit.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 2,
                'owner_type' => 'Project',
                'user_id' => 8,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Et sed sunt voluptas iste sunt voluptatem.',
                'description' => 'Incidunt quisquam blanditiis reiciendis quia culpa vel. Voluptas quis ut totam in sed quia blanditiis. Non aut aspernatur quae velit. Blanditiis necessitatibus eligendi in cupiditate.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 10,
                'owner_type' => 'Project',
                'user_id' => 9,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Illo quia dolorem nihil repellat unde sunt.',
                'description' => 'Quis incidunt ipsam in quia perferendis numquam et. Fugit magni est inventore est recusandae. Et neque consequatur beatae tempore natus dolores et. Aut et provident non laboriosam nisi at suscipit.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 3,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Sint sit ut eum quo nulla accusantium.',
                'description' => 'Iure totam ut sed tempora. Enim autem omnis temporibus non praesentium omnis fuga vel. Quia minima libero saepe non maxime nihil ab nam. Minus ipsa totam perspiciatis qui amet.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 6,
                'owner_type' => 'Project',
                'user_id' => 10,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Debitis voluptatem qui magni atque nobis totam.',
                'description' => 'Ut et ex est veniam sapiente sint. Ratione voluptatem qui hic perferendis. Itaque qui quos aut cupiditate quam in praesentium harum.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 6,
                'owner_type' => 'Project',
                'user_id' => 6,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Amet quas ea qui eum aliquam.',
                'description' => 'Fugiat dolore ea omnis odit nesciunt. Cumque quasi corrupti nostrum blanditiis. Doloribus sit maiores reprehenderit iure.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 5,
                'owner_type' => 'Project',
                'user_id' => 8,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Doloremque sunt alias nesciunt fugit cum.',
                'description' => 'Molestias est ea magnam tempora. Nostrum illo amet vitae ab quo ex molestiae soluta. Eos rerum ut voluptatem recusandae rerum occaecati.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 1,
                'owner_type' => 'Project',
                'user_id' => 7,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Neque minus quas est sit vel quos.',
                'description' => 'Quos veritatis officiis illum quam quam. Consectetur minus culpa consectetur distinctio quo. Velit non quia consequatur doloribus ut ut qui qui.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 8,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Eum laborum enim cumque neque.',
                'description' => 'Et sit at voluptates. Esse id est aut saepe. Illum incidunt nihil sit in vitae est nihil unde.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 10,
                'owner_type' => 'Project',
                'user_id' => 5,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Voluptatem nostrum omnis aut consequatur quis odit.',
                'description' => 'Quia ratione consequatur qui nulla ut labore nulla. Aut rem ratione provident tenetur aut. Explicabo ratione iusto voluptatem. Vero dolor nesciunt doloribus dolor magni qui.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 3,
                'owner_type' => 'Project',
                'user_id' => 4,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Vel tenetur quisquam similique amet.',
                'description' => 'Ab optio ut inventore sint. Distinctio cum id nulla omnis. Perferendis hic natus placeat dolores. Expedita totam dignissimos et cum.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 5,
                'owner_type' => 'Project',
                'user_id' => 3,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Soluta eligendi ut numquam et ex.',
                'description' => 'Voluptas voluptas quasi qui omnis. Esse dolores excepturi illo qui nihil non. Deserunt omnis sit commodi.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 1,
                'owner_type' => 'Project',
                'user_id' => 5,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Voluptas soluta et voluptatum impedit harum deserunt.',
                'description' => 'Sunt repudiandae quas occaecati voluptatum minus. Quod numquam aut consequatur omnis accusantium eligendi necessitatibus. Sapiente delectus optio id. Modi est sed non aut ea id error.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 9,
                'owner_type' => 'Project',
                'user_id' => 7,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Id aut nisi magni totam temporibus id sit.',
                'description' => 'Molestias et eius eos similique voluptatem. Eveniet et et est animi tempore quasi. Exercitationem quia pariatur aspernatur debitis ipsum voluptatem enim et.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 2,
                'owner_type' => 'Project',
                'user_id' => 2,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Mollitia sunt iste temporibus beatae fugiat.',
                'description' => 'Aut et molestias ab quia voluptatem eos. Aspernatur est vel occaecati ut aut. Tenetur adipisci cum natus sit.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 7,
                'owner_type' => 'Project',
                'user_id' => 7,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'In saepe consequatur autem quo facere repellendus.',
                'description' => 'Doloremque sed quidem veritatis eos quia. Minus in reiciendis iste esse aut optio nulla. Est culpa assumenda quod nobis. Hic earum voluptates qui autem. Eveniet aut velit quisquam vitae molestiae.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 10,
                'owner_type' => 'Project',
                'user_id' => 9,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Adipisci enim tenetur nisi similique.',
                'description' => 'Qui illo eius eveniet temporibus numquam quidem repellat officia. Repudiandae illo aliquam laudantium fuga rerum aut. Vel fugit ut sit at. Atque est iste ipsam assumenda reprehenderit sed minima.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 5,
                'owner_type' => 'Project',
                'user_id' => 10,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Ut nam consectetur dolores sit odit dolores.',
                'description' => 'Non culpa eligendi ut sunt aut. Alias quis molestiae eligendi in incidunt. Voluptatem sapiente laborum nihil rerum velit.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 7,
                'owner_type' => 'Project',
                'user_id' => 7,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
        ));
        
        
    }
}
