<?php

use Illuminate\Database\Seeder;

class ConversationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('conversations')->delete();
        
        \DB::table('conversations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Eius omnis exercitationem sed culpa.',
                'description' => 'Tempora voluptas et eius excepturi. Molestiae porro aspernatur doloribus voluptas. Porro veniam facere quis illum. Expedita ullam ut fugiat qui corrupti occaecati.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 7,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Totam eligendi eveniet ea ipsam.',
                'description' => 'Eaque quis pariatur laboriosam delectus fuga sapiente. Esse dicta ducimus at doloremque tempora repellendus omnis. Distinctio quasi rerum enim enim mollitia minus. Omnis qui maiores explicabo consequatur et nulla. Tempora inventore et et harum possimus ve',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 1,
                'owner_type' => 'Project',
                'user_id' => 4,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Minima ex qui dolor ab.',
                'description' => 'Adipisci quas unde doloremque dolorem totam est illo assumenda. Explicabo voluptate accusamus commodi est. Similique explicabo temporibus corrupti delectus provident aspernatur quam. Et eveniet a eligendi eum.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 8,
                'owner_type' => 'Project',
                'user_id' => 4,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Reiciendis consequatur odit magnam molestiae perferendis necessitatibus.',
                'description' => 'Id porro vel reiciendis modi. Et mollitia sed nihil praesentium id corrupti quasi. Aperiam autem amet et. Nihil consequatur aliquam quibusdam dicta ipsam consequuntur ut.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 10,
                'owner_type' => 'Project',
                'user_id' => 3,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Aut perspiciatis voluptas qui porro aut.',
                'description' => 'Corrupti autem quasi saepe et quisquam consequatur harum. Ab commodi non magnam optio maxime deleniti. Nesciunt quasi unde natus minus sequi voluptatem.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 6,
                'owner_type' => 'Project',
                'user_id' => 1,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Fugit quasi recusandae sed nam omnis animi.',
                'description' => 'In veniam itaque architecto aut. Officiis sunt aut consectetur. Quis et totam accusantium asperiores debitis omnis.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 6,
                'owner_type' => 'Project',
                'user_id' => 9,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Assumenda voluptatibus laborum et deserunt facilis fuga facilis.',
                'description' => 'Eos debitis dolores ut vero cupiditate. Omnis quasi illum odit quia ipsum quia fugit dolor. Qui excepturi necessitatibus tempora aperiam ut repudiandae sit. Dolor tempore fugiat earum occaecati atque exercitationem occaecati.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 3,
                'owner_type' => 'Project',
                'user_id' => 5,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Assumenda distinctio et dolorum aliquam provident dolorem explicabo.',
                'description' => 'Optio voluptatum ex fugit a sequi inventore. Dolorem iusto sit laboriosam aut mollitia. Blanditiis molestiae voluptatum tenetur corrupti beatae.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 3,
                'owner_type' => 'Project',
                'user_id' => 10,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Porro vel provident ut ipsam qui repellat.',
                'description' => 'Dolorem voluptatibus ut qui autem. Velit et et eius voluptate quod magni molestiae excepturi. Quia dolorum veritatis id nam. Voluptatem dolores nihil possimus quibusdam magni est.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 3,
                'owner_type' => 'Project',
                'user_id' => 9,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Est earum tempora quae ut vitae in.',
                'description' => 'Iure corrupti cupiditate officiis adipisci natus. Non vero magnam soluta. Illum soluta quod rerum placeat tenetur non et.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 9,
                'owner_type' => 'Project',
                'user_id' => 4,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Vero voluptatem sunt et maxime quo at omnis ut.',
                'description' => 'Molestiae maiores libero deserunt ducimus et et. Ullam odio consequatur facilis tempora eligendi in. Dignissimos et recusandae aut quia.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 8,
                'owner_type' => 'Project',
                'user_id' => 4,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Nihil temporibus velit dolorum qui est in quae.',
                'description' => 'Eum unde eos quisquam rem et aut. Occaecati nihil itaque adipisci et et sunt voluptas non. Autem quidem fugit libero.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 8,
                'owner_type' => 'Project',
                'user_id' => 2,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Non ut aliquid molestiae et suscipit aut aliquid molestiae.',
                'description' => 'Vero similique aliquid a esse dolore magni cumque in. Vel totam hic voluptas. Aut provident consectetur voluptatem enim.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 10,
                'owner_type' => 'Project',
                'user_id' => 10,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Delectus esse reprehenderit ad praesentium adipisci accusamus voluptas qui.',
                'description' => 'Sunt voluptatem eaque eum quas. Deserunt rerum deleniti excepturi ut autem animi officia. Quisquam sapiente adipisci accusamus ut asperiores. Voluptatibus ullam vel ipsum.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 3,
                'owner_type' => 'Project',
                'user_id' => 4,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Aliquid sed omnis qui et illum voluptas et omnis.',
                'description' => 'At at omnis est tempore voluptas quasi corporis et. Quis sapiente unde et ut quisquam possimus sequi qui. Quia rerum occaecati reprehenderit autem quaerat.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 5,
                'owner_type' => 'Project',
                'user_id' => 8,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Dolores adipisci dignissimos quia.',
                'description' => 'Molestiae debitis sed aut eos. Illum ea consequatur totam autem maxime. Omnis explicabo iure voluptas omnis distinctio maiores ut ipsum.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 6,
                'owner_type' => 'Project',
                'user_id' => 2,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Et quam minima mollitia tenetur.',
                'description' => 'Voluptatem commodi magnam quia sed repudiandae. Perferendis soluta laboriosam nobis tenetur.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 9,
                'owner_type' => 'Project',
                'user_id' => 7,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Hic illum reiciendis dolor in tenetur eligendi tempore.',
                'description' => 'Accusantium enim provident quis impedit harum et voluptatibus. Accusamus beatae quos ut nisi. Expedita itaque voluptatem rerum.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 5,
                'owner_type' => 'Project',
                'user_id' => 6,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Ut ut ducimus ut ut commodi neque perspiciatis.',
                'description' => 'Beatae veritatis velit laudantium aut est qui in minus. Ipsum iste quia tenetur et pariatur. Ut perspiciatis illo quia voluptas dolor vel.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 10,
                'owner_type' => 'Project',
                'user_id' => 5,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Corporis labore aspernatur vel sequi in dignissimos rem.',
                'description' => 'Aliquam rerum esse quaerat atque aut. Aliquam tempora consectetur error aut consectetur ratione. Voluptas illum eos aut non iste deleniti pariatur.',
                'description_height' => 40,
                'class' => 'info',
                'owner_id' => 8,
                'owner_type' => 'Project',
                'user_id' => 6,
                'facility_id' => 1,
                'tagged_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:38',
                'updated_at' => '2016-04-17 19:32:38',
            ),
        ));
        
        
    }
}
