<?php

use Illuminate\Database\Seeder;

class InventoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('inventories')->delete();
        
        \DB::table('inventories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'silver eos',
                'class' => 'info',
                'rfid' => '1414777e6c6b56269d0850959d18b1b4',
                'unit_count' => 95,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'aqua aspernatur',
                'class' => 'info',
                'rfid' => '44a8ae73fb607325d7c10ff151e807e3',
                'unit_count' => 58,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'yellow animi',
                'class' => 'info',
                'rfid' => '860f6db081feeee4a299761c21d2d264',
                'unit_count' => 62,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'maroon ut',
                'class' => 'info',
                'rfid' => 'b7775e583fa367ad4257f233fb44371a',
                'unit_count' => 35,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'navy dolorem',
                'class' => 'info',
                'rfid' => '3b828ceb62cf1957ba4d1a6b15cfd56a',
                'unit_count' => 94,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'olive possimus',
                'class' => 'info',
                'rfid' => 'c11b154b5b8b067da5289e8589f709a3',
                'unit_count' => 69,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'purple ipsa',
                'class' => 'info',
                'rfid' => '42bbe2736ee867ac94f6e00b7e97d286',
                'unit_count' => 93,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'blue inventore',
                'class' => 'info',
                'rfid' => 'fe641dd9d2c491f7820d8cdcc632e8a2',
                'unit_count' => 87,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'navy quia',
                'class' => 'info',
                'rfid' => '61271cd88f23913b2229273ddcdc43fb',
                'unit_count' => 66,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'navy quae',
                'class' => 'info',
                'rfid' => '6ea0c184786ed9779fd68e844ad72fd8',
                'unit_count' => 99,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'silver qui',
                'class' => 'info',
                'rfid' => 'f70d9a0dfc3fb1531e2285d0120fa782',
                'unit_count' => 77,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'fuchsia autem',
                'class' => 'info',
                'rfid' => 'd455625900f7aeba211fce29b4a8fba6',
                'unit_count' => 97,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'blue est',
                'class' => 'info',
                'rfid' => 'cbf917745682a96ac6c04efce6f14752',
                'unit_count' => 99,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'gray a',
                'class' => 'info',
                'rfid' => 'f3db1cbe68721a669f349b464516600f',
                'unit_count' => 12,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'black beatae',
                'class' => 'info',
                'rfid' => 'e37053c3f087fa162d9bd9ae330dfb08',
                'unit_count' => 100,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'navy id',
                'class' => 'info',
                'rfid' => '840bd3768591eb8e093fc9a8a0101c5b',
                'unit_count' => 69,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'purple voluptates',
                'class' => 'info',
                'rfid' => 'b6532a769948e552838915994f567db2',
                'unit_count' => 41,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'aqua repellat',
                'class' => 'info',
                'rfid' => '0ed89b2ed2d9e03b856be1436cb4e37b',
                'unit_count' => 91,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'maroon praesentium',
                'class' => 'info',
                'rfid' => 'c1f84430d6f4338d0efe394e17de8447',
                'unit_count' => 17,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'silver ipsam',
                'class' => 'info',
                'rfid' => '98225df8ffece01f59dd972d30710673',
                'unit_count' => 100,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'teal rerum',
                'class' => 'info',
                'rfid' => '47179add49b3c32fb5ff7d679d0123ff',
                'unit_count' => 19,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'purple architecto',
                'class' => 'info',
                'rfid' => '1b8790a433f78043adee07d1a6f85133',
                'unit_count' => 24,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'silver suscipit',
                'class' => 'info',
                'rfid' => 'aa6d9ba59eafd25bdc900e7e95d351e6',
                'unit_count' => 3,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'maroon quos',
                'class' => 'info',
                'rfid' => 'efde9aebf507f19ebc54c711c4d3878a',
                'unit_count' => 91,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'gray omnis',
                'class' => 'info',
                'rfid' => '7c316957c9e5a24cd08288cd3bbc27eb',
                'unit_count' => 78,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'yellow accusantium',
                'class' => 'info',
                'rfid' => '686ffc0688a8b276a69bd8cffbc2daed',
                'unit_count' => 95,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'purple eaque',
                'class' => 'info',
                'rfid' => 'b974fbbfcbc3b389638deedd998c0f91',
                'unit_count' => 51,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'yellow aliquid',
                'class' => 'info',
                'rfid' => '3c881a8be7d94fdedd8ae83fbffae399',
                'unit_count' => 55,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'olive ad',
                'class' => 'info',
                'rfid' => '7ece1d0b86c1f1815684f07a69b4686c',
                'unit_count' => 4,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'lime molestiae',
                'class' => 'info',
                'rfid' => 'a7c56c232c3141c0d930d208d73c6f7a',
                'unit_count' => 90,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'black ea',
                'class' => 'info',
                'rfid' => 'e7231489cfee6e2fcdf13fa38bfa1c60',
                'unit_count' => 78,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'gray est',
                'class' => 'info',
                'rfid' => '3d560c0c21c6084999e041daf20ae63f',
                'unit_count' => 62,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'navy nobis',
                'class' => 'info',
                'rfid' => '027be1a654e337449b6f15e8d7ea1d96',
                'unit_count' => 99,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'black sapiente',
                'class' => 'info',
                'rfid' => '3c04bb190db80d6e6adacf7537dcff5d',
                'unit_count' => 51,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'lime consequatur',
                'class' => 'info',
                'rfid' => 'f3fedb9bf3215201384150d00c3d94a7',
                'unit_count' => 52,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'olive exercitationem',
                'class' => 'info',
                'rfid' => '35ab7775c1ff80999c4b4489fca786b6',
                'unit_count' => 95,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'maroon magni',
                'class' => 'info',
                'rfid' => 'cb81a952f01b25ae1ebae8ba5034484b',
                'unit_count' => 50,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'lime corrupti',
                'class' => 'info',
                'rfid' => '727cff6fe4be0220de887af6f706ad49',
                'unit_count' => 9,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'blue perferendis',
                'class' => 'info',
                'rfid' => 'df19e255252d3ccc8902aa59065fc948',
                'unit_count' => 59,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'teal odit',
                'class' => 'info',
                'rfid' => '4d052c9bf433531114b8204cdb118fa1',
                'unit_count' => 65,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'yellow voluptas',
                'class' => 'info',
                'rfid' => 'aca55ccdf607c42677e87d2523c2ec8a',
                'unit_count' => 24,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'purple aspernatur',
                'class' => 'info',
                'rfid' => 'fab3ac559d5a3df5d170ebc92f480659',
                'unit_count' => 15,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'black sit',
                'class' => 'info',
                'rfid' => '40a3eed8bc00c5cdc8a7c053b210f862',
                'unit_count' => 33,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'purple corrupti',
                'class' => 'info',
                'rfid' => '5d8c7f7d26f2d94aef4139225154d3f6',
                'unit_count' => 77,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'purple quos',
                'class' => 'info',
                'rfid' => 'af7e29b346d63f03e365d6e0a2a03edf',
                'unit_count' => 57,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'black eligendi',
                'class' => 'info',
                'rfid' => '4c0dcac4e98cfaabc07ff065e28eae9b',
                'unit_count' => 74,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'maroon tenetur',
                'class' => 'info',
                'rfid' => 'e0f9fbc5602bd3b7f36dded20340043d',
                'unit_count' => 97,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'aqua ut',
                'class' => 'info',
                'rfid' => 'f08591d8d7d7325d0c0482e06da7c0c3',
                'unit_count' => 66,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'silver id',
                'class' => 'info',
                'rfid' => 'dd94632285268a00781577f70fd82f2f',
                'unit_count' => 72,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'fuchsia sint',
                'class' => 'info',
                'rfid' => '4eb64bcce019149b33a1512364f7c00f',
                'unit_count' => 31,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'silver sed',
                'class' => 'info',
                'rfid' => 'ea78622cc106956bde28de2d9f65267f',
                'unit_count' => 44,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'aqua voluptatem',
                'class' => 'info',
                'rfid' => '43ab32d68b8a3a259f85a1d733c2804d',
                'unit_count' => 29,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'fuchsia molestiae',
                'class' => 'info',
                'rfid' => 'cf6032b5bb7cad40b10cc5c4f715710c',
                'unit_count' => 8,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'gray libero',
                'class' => 'info',
                'rfid' => '8f3532e6c79b187fd325515604b9b52c',
                'unit_count' => 86,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'silver nesciunt',
                'class' => 'info',
                'rfid' => '5d93abad31088bced2aa54ff9c05de93',
                'unit_count' => 51,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'aqua est',
                'class' => 'info',
                'rfid' => '360e4fd94e0e7b3bee45bd60c82dc1a5',
                'unit_count' => 83,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'purple eaque',
                'class' => 'info',
                'rfid' => '3b5b289b03403c92290888eff6444ef6',
                'unit_count' => 76,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'aqua impedit',
                'class' => 'info',
                'rfid' => '19343046aaefba267887aa064fed9d3e',
                'unit_count' => 80,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'green incidunt',
                'class' => 'info',
                'rfid' => '078f569d32ff656f599d59d5e2f3460b',
                'unit_count' => 51,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'blue quisquam',
                'class' => 'info',
                'rfid' => '261f2675ebfe3a01bf42a1c32537fc87',
                'unit_count' => 90,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'olive incidunt',
                'class' => 'info',
                'rfid' => '8f9f743a1271074550bd46a3ae091db8',
                'unit_count' => 90,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'maroon itaque',
                'class' => 'info',
                'rfid' => '507845c53bdc2576cb246d2f2d5e8455',
                'unit_count' => 27,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'aqua accusantium',
                'class' => 'info',
                'rfid' => '569c6e2d670963d231e0f60d1470335b',
                'unit_count' => 64,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'navy at',
                'class' => 'info',
                'rfid' => '3c16dbcdba99d7e8fe71d7201aec3b96',
                'unit_count' => 99,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'teal omnis',
                'class' => 'info',
                'rfid' => '649f76618de5a60a4d004654dc7e69f3',
                'unit_count' => 82,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'teal amet',
                'class' => 'info',
                'rfid' => '1d551f383b45422f7b0f34c86c61ffcf',
                'unit_count' => 64,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'yellow ullam',
                'class' => 'info',
                'rfid' => 'c048d9773d343961222c86c469c77298',
                'unit_count' => 41,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'lime aspernatur',
                'class' => 'info',
                'rfid' => '46f92f8986de45a907e0f3e48447ebcd',
                'unit_count' => 62,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'lime molestias',
                'class' => 'info',
                'rfid' => '26ae17435462abaa53a0ee0f95ae05ee',
                'unit_count' => 34,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'teal sed',
                'class' => 'info',
                'rfid' => '1fea2747807daa64a5410be898cadb7e',
                'unit_count' => 18,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'fuchsia unde',
                'class' => 'info',
                'rfid' => 'b36669a42fbf065b500b1149ff81e300',
                'unit_count' => 77,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'olive veniam',
                'class' => 'info',
                'rfid' => '6544d0b2b6f0a1c845c58961904d60b9',
                'unit_count' => 36,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'aqua dolores',
                'class' => 'info',
                'rfid' => '63150fa5fafd970b4993e084f516fb9f',
                'unit_count' => 8,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'maroon repellat',
                'class' => 'info',
                'rfid' => '967e14c332b82df40dfded6c7473f165',
                'unit_count' => 27,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'aqua quis',
                'class' => 'info',
                'rfid' => '8e6379f0398d08bb4c282e8a1ffd8f5b',
                'unit_count' => 69,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'blue beatae',
                'class' => 'info',
                'rfid' => 'f74b7dcf61f4975de239ce5e2150451b',
                'unit_count' => 89,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'white quasi',
                'class' => 'info',
                'rfid' => '740a85622559e7761addc845b120ad1e',
                'unit_count' => 63,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'teal dolor',
                'class' => 'info',
                'rfid' => '6f68c90f7b1a24878fb5381452829e5c',
                'unit_count' => 87,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'gray molestias',
                'class' => 'info',
                'rfid' => '437e729df95919cec8d588c4995482eb',
                'unit_count' => 24,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'white odio',
                'class' => 'info',
                'rfid' => 'eed6c30c4ad1aeaa177e4082ea5d31b3',
                'unit_count' => 48,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'maroon tenetur',
                'class' => 'info',
                'rfid' => '17f0e5b6a80b8df10cac4f5028a3ec27',
                'unit_count' => 88,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'green deserunt',
                'class' => 'info',
                'rfid' => 'd2a5d549d34ba0f8b682f60e5a5971a2',
                'unit_count' => 89,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'teal soluta',
                'class' => 'info',
                'rfid' => 'a5aefe867dd13fee5a5848fc428b294e',
                'unit_count' => 79,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'black saepe',
                'class' => 'info',
                'rfid' => '82c658cbf7713add8748e7749fea04c7',
                'unit_count' => 66,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:34',
                'updated_at' => '2016-04-19 08:09:34',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'aqua perferendis',
                'class' => 'info',
                'rfid' => '097ab006fba55c1fbf721eae74c6b0aa',
                'unit_count' => 35,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'maroon ipsam',
                'class' => 'info',
                'rfid' => 'e4add7c71c462d0a42a4e54b8bf75545',
                'unit_count' => 37,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'white sit',
                'class' => 'info',
                'rfid' => '1f67ef34a0ae592e8793a8b0b9d02da4',
                'unit_count' => 54,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'purple totam',
                'class' => 'info',
                'rfid' => '489e99c240d805930deefa52504036c7',
                'unit_count' => 63,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'aqua est',
                'class' => 'info',
                'rfid' => '412b90cb3a9b9a2f5c6d3f373b1d32c0',
                'unit_count' => 43,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'silver eaque',
                'class' => 'info',
                'rfid' => '0a597e645de90cc814af048d89aca485',
                'unit_count' => 44,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'teal et',
                'class' => 'info',
                'rfid' => 'b681c8118b45d5cc78a3e3ae38e490e7',
                'unit_count' => 57,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'olive ut',
                'class' => 'info',
                'rfid' => '54e02dccd4ffbd016fdc5e9440d2e9b4',
                'unit_count' => 71,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'green maiores',
                'class' => 'info',
                'rfid' => '76a12bb35661e008ef019de8cf7dfb88',
                'unit_count' => 12,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'blue necessitatibus',
                'class' => 'info',
                'rfid' => 'e39942a803e074990d8e710933f0906b',
                'unit_count' => 45,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'lime pariatur',
                'class' => 'info',
                'rfid' => '707d9d743df6abeeefe21191e156c439',
                'unit_count' => 66,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'green debitis',
                'class' => 'info',
                'rfid' => 'db6d30f33e0b3617d5a9b8e29affc716',
                'unit_count' => 58,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'aqua voluptatum',
                'class' => 'info',
                'rfid' => 'ccff78f58b436b60efe65b3b62d975de',
                'unit_count' => 84,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'silver consectetur',
                'class' => 'info',
                'rfid' => '1184e6232cc5f9ac44f979af8fb7ce4f',
                'unit_count' => 85,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'olive aut',
                'class' => 'info',
                'rfid' => 'e80b8ed3ba5f9c29edaef34b772edeeb',
                'unit_count' => 22,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'purple tempore',
                'class' => 'info',
                'rfid' => '01f412fbf51a47417635b290bc764f8c',
                'unit_count' => 28,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 08:09:35',
                'updated_at' => '2016-04-19 08:09:35',
            ),
        ));
        
        
    }
}
