<?php

use Illuminate\Database\Seeder;

class InventoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('inventories')->delete();
        
        \DB::table('inventories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'silver quidem',
                'class' => 'info',
                'rfid' => '97ce39461de18c3904eb7db076367807',
                'unit_count' => 22,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'blue enim',
                'class' => 'info',
                'rfid' => 'cd521baeb399b83caa09b890bef83451',
                'unit_count' => 2,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'black dolor',
                'class' => 'info',
                'rfid' => '890b084695590309268d996ddd90b96a',
                'unit_count' => 10,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'gray vero',
                'class' => 'info',
                'rfid' => '4b782a4a8afff52705519cefc0169b42',
                'unit_count' => 71,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'fuchsia aut',
                'class' => 'info',
                'rfid' => '58d7c3cb6748634ba0e5cea71b191f37',
                'unit_count' => 72,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'teal hic',
                'class' => 'info',
                'rfid' => '835f9674a3b679a7cc31b3a6766d86a5',
                'unit_count' => 75,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'yellow minus',
                'class' => 'info',
                'rfid' => '1873ecf5af5b3b98efad4294052185c4',
                'unit_count' => 53,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'silver asperiores',
                'class' => 'info',
                'rfid' => 'a8dfcac5f373f7335857922a7afe1eba',
                'unit_count' => 3,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'purple sapiente',
                'class' => 'info',
                'rfid' => 'f44e7b8b53050437b0c489d67768fbc6',
                'unit_count' => 44,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'gray consequatur',
                'class' => 'info',
                'rfid' => 'adfb0fa9201ceb0bd882d634b55c56a4',
                'unit_count' => 89,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'olive neque',
                'class' => 'info',
                'rfid' => '2f5fb931f14bf339769ce5fdb67fd6ab',
                'unit_count' => 66,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'gray dolore',
                'class' => 'info',
                'rfid' => 'cff1d42cf7524de01c44cbaaa68c4ed3',
                'unit_count' => 31,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'black nam',
                'class' => 'info',
                'rfid' => '421d164c6df87264c45065a2c095711d',
                'unit_count' => 46,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'olive ad',
                'class' => 'info',
                'rfid' => '48c6ff877c60262fa60b32e8a075c766',
                'unit_count' => 85,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'yellow quo',
                'class' => 'info',
                'rfid' => 'e1fe208a5a41f44f1623c74509c26d04',
                'unit_count' => 76,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'black beatae',
                'class' => 'info',
                'rfid' => '450a0f64bdf405eb7ee1e9df6cd1f5ab',
                'unit_count' => 24,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'fuchsia sed',
                'class' => 'info',
                'rfid' => '554d89541b227ae5a9d7f4f6c32eed6a',
                'unit_count' => 75,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'lime totam',
                'class' => 'info',
                'rfid' => 'a6b209eb232625e410446d26672fed9b',
                'unit_count' => 79,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'navy expedita',
                'class' => 'info',
                'rfid' => 'de01e9797648b5167be03f2ff2034d57',
                'unit_count' => 11,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'white velit',
                'class' => 'info',
                'rfid' => 'f09a7b694e97364478bd87f5e2fc3065',
                'unit_count' => 16,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'lime nam',
                'class' => 'info',
                'rfid' => '9a12c5e7616c83e41d6acadd6d51f97b',
                'unit_count' => 21,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'gray et',
                'class' => 'info',
                'rfid' => 'b8551105dd4deb9aa0c0e11eab5a00c4',
                'unit_count' => 61,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'olive voluptate',
                'class' => 'info',
                'rfid' => 'c31813157af5a81f2ee8a27b30492eb1',
                'unit_count' => 97,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'blue dolores',
                'class' => 'info',
                'rfid' => 'ceb5f428349b52d79ffbf353bd9a748d',
                'unit_count' => 28,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'white et',
                'class' => 'info',
                'rfid' => '08c7eca6171934da43295f0caa9e2755',
                'unit_count' => 8,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'yellow porro',
                'class' => 'info',
                'rfid' => 'f10877a1904a13258bf237da64e2bdec',
                'unit_count' => 69,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'teal quis',
                'class' => 'info',
                'rfid' => 'b3f18882d1b10f7bccd42133f429fc65',
                'unit_count' => 45,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'yellow aut',
                'class' => 'info',
                'rfid' => '095e48e6db0a66730afe28c45fb5e189',
                'unit_count' => 21,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'white architecto',
                'class' => 'info',
                'rfid' => 'bd15704c92989216cc8e6e0a4143956d',
                'unit_count' => 30,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'teal distinctio',
                'class' => 'info',
                'rfid' => '043f010958541a49662b1edff2b9ab34',
                'unit_count' => 98,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'lime sint',
                'class' => 'info',
                'rfid' => '6ff8b7d1acf841c8762a29e3b7555276',
                'unit_count' => 74,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'navy architecto',
                'class' => 'info',
                'rfid' => 'a57a438f857ffd2a1a4bad2b23c9f777',
                'unit_count' => 78,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'white qui',
                'class' => 'info',
                'rfid' => '80db2f41f87b6b2f313a26acabf9d867',
                'unit_count' => 11,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'navy beatae',
                'class' => 'info',
                'rfid' => '5694f5008fd53bd974ff5d816409e8f6',
                'unit_count' => 84,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'gray qui',
                'class' => 'info',
                'rfid' => '43fc177aa5810b814da72f6d8b7115d1',
                'unit_count' => 67,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'silver sint',
                'class' => 'info',
                'rfid' => '8e03c5e3122fbccc08833a316ab95951',
                'unit_count' => 30,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'yellow ducimus',
                'class' => 'info',
                'rfid' => 'c55d64946b3cd5543e71e09ca175a998',
                'unit_count' => 50,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'navy nulla',
                'class' => 'info',
                'rfid' => 'c5e4761b70edb9aa1e7be807af90b1b7',
                'unit_count' => 77,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'green itaque',
                'class' => 'info',
                'rfid' => 'dad80ae74176fdcd4f516abd77d379a6',
                'unit_count' => 15,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'lime saepe',
                'class' => 'info',
                'rfid' => 'abc86087ea4b7302e05a099b42562f9f',
                'unit_count' => 7,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'navy ex',
                'class' => 'info',
                'rfid' => '87c46043c01490040e3a6bd072680426',
                'unit_count' => 41,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'blue animi',
                'class' => 'info',
                'rfid' => '483303f8e0af0a9d6252ef9b8c951ca6',
                'unit_count' => 83,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'lime non',
                'class' => 'info',
                'rfid' => '091120c7d7a907019b2225e9ba2ee3e6',
                'unit_count' => 62,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'lime laborum',
                'class' => 'info',
                'rfid' => '1d3db0669ceeefe7419d5d27e88cc3da',
                'unit_count' => 25,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'blue sint',
                'class' => 'info',
                'rfid' => '4bf40438c78c17c8fe5db111bce53758',
                'unit_count' => 56,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'maroon ratione',
                'class' => 'info',
                'rfid' => 'afe112705bbae77e82af98f40226b854',
                'unit_count' => 30,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'teal soluta',
                'class' => 'info',
                'rfid' => '6271458d9a6cab58bf95c2518da000aa',
                'unit_count' => 71,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'teal porro',
                'class' => 'info',
                'rfid' => '3a3bf6aa1a516b3d3c12121f6c26fc6a',
                'unit_count' => 55,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'yellow praesentium',
                'class' => 'info',
                'rfid' => '6e94bdc5ec81d16865f1e9cfd37db053',
                'unit_count' => 58,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'yellow commodi',
                'class' => 'info',
                'rfid' => '7637d422dc50184940444d40555fbd7d',
                'unit_count' => 93,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'fuchsia ullam',
                'class' => 'info',
                'rfid' => 'fb14273235cd9da04f490a4973ddc8e3',
                'unit_count' => 74,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'blue rem',
                'class' => 'info',
                'rfid' => 'cfab91ba21d5d548314b7fd3372b5172',
                'unit_count' => 22,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'fuchsia et',
                'class' => 'info',
                'rfid' => '0ace9b1baddf728a39e266e62df15192',
                'unit_count' => 97,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'maroon debitis',
                'class' => 'info',
                'rfid' => '84ffe355d11e8b8e76fb654ccdb0ef73',
                'unit_count' => 96,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'green reprehenderit',
                'class' => 'info',
                'rfid' => 'ed3b04f6b12f9d04d5803f1cec73aaad',
                'unit_count' => 44,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'silver et',
                'class' => 'info',
                'rfid' => '9f0cc4f64b87e24508c26e44210977de',
                'unit_count' => 52,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'purple explicabo',
                'class' => 'info',
                'rfid' => 'ab210db502c9c87ed57c3af417c90324',
                'unit_count' => 86,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'maroon quis',
                'class' => 'info',
                'rfid' => 'b34ae8b3d1488db792a2975ab131186e',
                'unit_count' => 92,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'gray hic',
                'class' => 'info',
                'rfid' => 'a4b48af959c3c33ea993ceaaad9f6929',
                'unit_count' => 89,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'white quae',
                'class' => 'info',
                'rfid' => 'd4041f4dca1924f153d25d02f935026f',
                'unit_count' => 9,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'white sed',
                'class' => 'info',
                'rfid' => '82c547f9ae37a063d5cd8db5c228a891',
                'unit_count' => 47,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'maroon autem',
                'class' => 'info',
                'rfid' => 'b455e1d53c53965dec19a9b99ede4123',
                'unit_count' => 78,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'aqua tenetur',
                'class' => 'info',
                'rfid' => '10829ac46596722f6626c30377e925ef',
                'unit_count' => 78,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'maroon nihil',
                'class' => 'info',
                'rfid' => '7ef8ddcafe89ae57b7d38645688b874c',
                'unit_count' => 59,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'navy reprehenderit',
                'class' => 'info',
                'rfid' => 'ec0e2aa8fb17fb877385f4168d7bb4b1',
                'unit_count' => 4,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'fuchsia officia',
                'class' => 'info',
                'rfid' => '3cd9a15b9c47596088359f8b6acc2fed',
                'unit_count' => 79,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'white quia',
                'class' => 'info',
                'rfid' => '15659a60b979b88967f8cf7047fafbb3',
                'unit_count' => 14,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'gray eligendi',
                'class' => 'info',
                'rfid' => 'bb8b040d65833824c191be34c2213be7',
                'unit_count' => 59,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'black qui',
                'class' => 'info',
                'rfid' => '6a429b4c0af0556119115e3ed667308e',
                'unit_count' => 89,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'white labore',
                'class' => 'info',
                'rfid' => 'b8c93335008e6aa84cc5dabd7771f4f6',
                'unit_count' => 20,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'green pariatur',
                'class' => 'info',
                'rfid' => 'a92997567bc0d54516a0459f465b2439',
                'unit_count' => 58,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'green repudiandae',
                'class' => 'info',
                'rfid' => '2be17e38b748011d6adeb210b0c0f00d',
                'unit_count' => 43,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'teal blanditiis',
                'class' => 'info',
                'rfid' => '4bc5216726c762a3e4839092de5d50df',
                'unit_count' => 59,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'purple et',
                'class' => 'info',
                'rfid' => 'eee6e3bbdaba212d65ba6b366c6296e7',
                'unit_count' => 68,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'aqua illo',
                'class' => 'info',
                'rfid' => '56e80cd8494dbe02c346121465c53b44',
                'unit_count' => 93,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'green voluptatem',
                'class' => 'info',
                'rfid' => '452d5a701c0c1a2530ea6cac86885e37',
                'unit_count' => 90,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'white molestias',
                'class' => 'info',
                'rfid' => '1c118abf322b66c3c4129dd2467e752e',
                'unit_count' => 89,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'maroon rerum',
                'class' => 'info',
                'rfid' => 'd719a6b54886efd5ce592136c6736f83',
                'unit_count' => 61,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'gray et',
                'class' => 'info',
                'rfid' => 'd7e4e0d2e5b0e6287ca0461f466f0e91',
                'unit_count' => 59,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'teal architecto',
                'class' => 'info',
                'rfid' => '54131fa15997a595cf4f0031bcc69e6c',
                'unit_count' => 42,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'maroon veniam',
                'class' => 'info',
                'rfid' => 'aa4bebd2b5b5011bac7d6a00a2d9a917',
                'unit_count' => 2,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'aqua aut',
                'class' => 'info',
                'rfid' => 'c41e7e75412881d3cf7919aedebf2e83',
                'unit_count' => 13,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'aqua deleniti',
                'class' => 'info',
                'rfid' => 'ae2ddead35fd0fe7c57ce77662252140',
                'unit_count' => 97,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'blue animi',
                'class' => 'info',
                'rfid' => '78baddbbbba7f8f8b2c2b876789ce327',
                'unit_count' => 50,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'maroon vel',
                'class' => 'info',
                'rfid' => 'f9479cf563a4b182b46da8a099e1e25e',
                'unit_count' => 68,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'gray voluptatem',
                'class' => 'info',
                'rfid' => '500b977d5ed7a86217dba53bb5ec7b46',
                'unit_count' => 94,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'gray iure',
                'class' => 'info',
                'rfid' => '4818f6c2c630e3eef26b12a9138468bc',
                'unit_count' => 80,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'green qui',
                'class' => 'info',
                'rfid' => '3e5dc3391f03d20a582d5aaa5e28f98b',
                'unit_count' => 12,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'navy ex',
                'class' => 'info',
                'rfid' => 'cc673164172660bf3403a074e90ec327',
                'unit_count' => 81,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'gray voluptas',
                'class' => 'info',
                'rfid' => 'c0ff02ed826c18b0e5e6780204d7a050',
                'unit_count' => 75,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'gray reprehenderit',
                'class' => 'info',
                'rfid' => '08d3580c0af0b70e18afc630b61384df',
                'unit_count' => 4,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'green illum',
                'class' => 'info',
                'rfid' => '4c3d80938110d952d6792d287cd65948',
                'unit_count' => 13,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'white cupiditate',
                'class' => 'info',
                'rfid' => 'ee082a71ae0b51610a3ad7f644420d00',
                'unit_count' => 79,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'blue exercitationem',
                'class' => 'info',
                'rfid' => 'fa093744f109809bda93de524cfe177f',
                'unit_count' => 80,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'white deleniti',
                'class' => 'info',
                'rfid' => 'b026585082bcbd036498986b7e6ab791',
                'unit_count' => 75,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'olive assumenda',
                'class' => 'info',
                'rfid' => '57166db62105141f30fa4cf6a4ea39e4',
                'unit_count' => 66,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'aqua earum',
                'class' => 'info',
                'rfid' => '672634bff896292a85cde6e04d512347',
                'unit_count' => 33,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'teal omnis',
                'class' => 'info',
                'rfid' => '6ab24d258ebe101f61900652a8eeaf9c',
                'unit_count' => 88,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'aqua laboriosam',
                'class' => 'info',
                'rfid' => '075f84f0d33a25d19a405d8f82bd7ab0',
                'unit_count' => 91,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'green quas',
                'class' => 'info',
                'rfid' => 'c2aec2cc1713e416d0be293d3e451af3',
                'unit_count' => 29,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:56',
                'updated_at' => '2016-04-25 06:18:56',
            ),
        ));
        
        
    }
}
