<?php

use Illuminate\Database\Seeder;

class InventoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('inventories')->delete();
        
        \DB::table('inventories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'aqua itaque',
                'class' => 'info',
                'rfid' => 'f2dddc8a50d8d12c9f5f2c0803e0d54c',
                'unit_count' => 100,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'green optio',
                'class' => 'info',
                'rfid' => '55005f01494202842e801e3016ce9020',
                'unit_count' => 19,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'fuchsia harum',
                'class' => 'info',
                'rfid' => '434364268b61a593627c8fa178f7b350',
                'unit_count' => 75,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'yellow nemo',
                'class' => 'info',
                'rfid' => '1d28840022b29a495299743b1ba02c5f',
                'unit_count' => 82,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'white ut',
                'class' => 'info',
                'rfid' => '003466a307edc4737b3bb262aa7b1910',
                'unit_count' => 1,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'blue non',
                'class' => 'info',
                'rfid' => '617ebc427c945673ef145787e39697fb',
                'unit_count' => 7,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'green omnis',
                'class' => 'info',
                'rfid' => '257e209a582a8fa4c51def649d790da0',
                'unit_count' => 22,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'aqua quidem',
                'class' => 'info',
                'rfid' => '939eb8be56b7f61707a413b6bc58ea64',
                'unit_count' => 17,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'black ad',
                'class' => 'info',
                'rfid' => 'c1b9f20a2581968a799e3931000e4db6',
                'unit_count' => 15,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'green dolor',
                'class' => 'info',
                'rfid' => '1d62860eab2db9ec31f972ec0a946cf0',
                'unit_count' => 18,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'white minima',
                'class' => 'info',
                'rfid' => '287cc00ecb2db393b37a808965501cf5',
                'unit_count' => 3,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'maroon sit',
                'class' => 'info',
                'rfid' => '794d2699d59ce2ac7f88c0e2b377fd81',
                'unit_count' => 3,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'silver voluptatem',
                'class' => 'info',
                'rfid' => 'fc398cb677a7b6b032f4ab0740ff4f6a',
                'unit_count' => 42,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'purple laudantium',
                'class' => 'info',
                'rfid' => '54af18cb33b9c3df31570c22f0cecc3a',
                'unit_count' => 32,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'silver quibusdam',
                'class' => 'info',
                'rfid' => 'af6f4bfc878876565146b3015255e4ee',
                'unit_count' => 5,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'green quae',
                'class' => 'info',
                'rfid' => 'ab2be459b62ca00df155774a5ef3aedf',
                'unit_count' => 63,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'yellow eius',
                'class' => 'info',
                'rfid' => '845a1b4ebce51c15a19e97827f5d3706',
                'unit_count' => 44,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'gray necessitatibus',
                'class' => 'info',
                'rfid' => 'a769082b59f2daaaf5ae3d0135ffb379',
                'unit_count' => 12,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'green in',
                'class' => 'info',
                'rfid' => 'ddf38cde0359376b9dd008b2641f07a7',
                'unit_count' => 19,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'navy quam',
                'class' => 'info',
                'rfid' => 'd11e5b8759e237a6600f9f9b5b4f72ef',
                'unit_count' => 32,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'black ut',
                'class' => 'info',
                'rfid' => 'e3e7e92ea26cf6f75a77eab5cbf3cded',
                'unit_count' => 1,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'purple vitae',
                'class' => 'info',
                'rfid' => 'e5cbc331cf04a31b27dcda790199879f',
                'unit_count' => 99,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'silver vitae',
                'class' => 'info',
                'rfid' => '4c5514bf59a85a1c42140dae82703cab',
                'unit_count' => 49,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'silver modi',
                'class' => 'info',
                'rfid' => '1e2f81f69f3f6168d51c4273f2b4b6e9',
                'unit_count' => 59,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'aqua repellat',
                'class' => 'info',
                'rfid' => 'e6e447806082d1f7ac725ef7b259fc64',
                'unit_count' => 87,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'gray vel',
                'class' => 'info',
                'rfid' => '79132ef11234887d17bd8e05c9efe2c0',
                'unit_count' => 87,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'aqua et',
                'class' => 'info',
                'rfid' => 'f6d0c7c1984e069c9f827db9e1523a34',
                'unit_count' => 28,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'maroon sint',
                'class' => 'info',
                'rfid' => '490c005bb4fdca5abc2bf160cb2fe7fc',
                'unit_count' => 76,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'maroon earum',
                'class' => 'info',
                'rfid' => 'a9999d91fcde1fac76423950e797b24e',
                'unit_count' => 56,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'white fugit',
                'class' => 'info',
                'rfid' => '8ff9c79660ded9db59e3235b8ee3ba06',
                'unit_count' => 45,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'yellow et',
                'class' => 'info',
                'rfid' => '169ad0857bf54ed1d46594a123263676',
                'unit_count' => 42,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'yellow eaque',
                'class' => 'info',
                'rfid' => '4affa78eb2669d1993315fbea80f2da4',
                'unit_count' => 47,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'silver at',
                'class' => 'info',
                'rfid' => 'f3f9a523dea6d9904f465648e6b83e43',
                'unit_count' => 78,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'aqua facere',
                'class' => 'info',
                'rfid' => '3bacb21fd9f5c813c90de0474e78dc9f',
                'unit_count' => 11,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'black et',
                'class' => 'info',
                'rfid' => '2947cd59460386b7ea4415d1aa9f4beb',
                'unit_count' => 26,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'silver aut',
                'class' => 'info',
                'rfid' => 'e2f552526b2c2e7532fea659ea226c3a',
                'unit_count' => 25,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'teal sit',
                'class' => 'info',
                'rfid' => '1752a01448495e2cb6b16c1ded88e631',
                'unit_count' => 15,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'white et',
                'class' => 'info',
                'rfid' => '93ced638e302de237c431f1d448a150a',
                'unit_count' => 15,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'lime quae',
                'class' => 'info',
                'rfid' => 'bb48de4310b1bb379b81cfa295764068',
                'unit_count' => 44,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'gray nulla',
                'class' => 'info',
                'rfid' => '749808e7425a91c8b73cd0cb37e5bc7e',
                'unit_count' => 15,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'teal nesciunt',
                'class' => 'info',
                'rfid' => '26617af6fd306ee3c26bc4ff66549e09',
                'unit_count' => 46,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'fuchsia quasi',
                'class' => 'info',
                'rfid' => '08c7b69fe9f1bf47de049ec272651a6e',
                'unit_count' => 39,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'purple ad',
                'class' => 'info',
                'rfid' => '4b87f30c2d46298aeb51190bd457be48',
                'unit_count' => 98,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'olive ipsum',
                'class' => 'info',
                'rfid' => '287dece391904a299a1fb5a348b152bc',
                'unit_count' => 63,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'aqua voluptatem',
                'class' => 'info',
                'rfid' => '5ddc39c2b6c3994b39d22afdf21946c8',
                'unit_count' => 67,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'olive non',
                'class' => 'info',
                'rfid' => '6cf5c8f1369184ade961452435125f2b',
                'unit_count' => 13,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'fuchsia sed',
                'class' => 'info',
                'rfid' => '1bf52f5a6ba6268d66ff0cf45e17ff82',
                'unit_count' => 66,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'yellow dicta',
                'class' => 'info',
                'rfid' => 'dbbd7983901458e2f8c597463c828efa',
                'unit_count' => 68,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'maroon optio',
                'class' => 'info',
                'rfid' => '7a050300e62cb64d267b08eee50a8666',
                'unit_count' => 31,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'blue mollitia',
                'class' => 'info',
                'rfid' => '6c0d625932a8c202de6abdc12dac1e6f',
                'unit_count' => 74,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'purple velit',
                'class' => 'info',
                'rfid' => 'efa1ab356e22fb6ca88565f7c242c794',
                'unit_count' => 29,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'olive eligendi',
                'class' => 'info',
                'rfid' => '88efc79830f13effd03bc6d07ac3eb32',
                'unit_count' => 95,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'fuchsia culpa',
                'class' => 'info',
                'rfid' => '76cddc0a08b03283b6977f0c57eb7af8',
                'unit_count' => 73,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'white officiis',
                'class' => 'info',
                'rfid' => '71870e9799dbcb876c777f841510d2aa',
                'unit_count' => 9,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'purple doloremque',
                'class' => 'info',
                'rfid' => '6d53e4a94f71b3524d2d36b1949a77ca',
                'unit_count' => 63,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'lime perspiciatis',
                'class' => 'info',
                'rfid' => 'df0892cde68cb0f49528c9b75715dc82',
                'unit_count' => 21,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'black eos',
                'class' => 'info',
                'rfid' => 'bae5e701f102aaa4456b0a8d638fe755',
                'unit_count' => 70,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'silver voluptate',
                'class' => 'info',
                'rfid' => 'fa71e4eebf46dc2506977c83dbc7a46d',
                'unit_count' => 38,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'black odio',
                'class' => 'info',
                'rfid' => '050aaf8523154321d0378df3d3a23502',
                'unit_count' => 99,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'yellow et',
                'class' => 'info',
                'rfid' => '006ee52fbbcc600742ee59927df051e9',
                'unit_count' => 9,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'purple aut',
                'class' => 'info',
                'rfid' => 'a2ae6820202266e7c5d57dafa33e2ea9',
                'unit_count' => 13,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'blue eius',
                'class' => 'info',
                'rfid' => 'bbe4514759ea55570165837bf6369517',
                'unit_count' => 52,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'blue mollitia',
                'class' => 'info',
                'rfid' => '07708992b5273a46d58894dfb5595d2f',
                'unit_count' => 73,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'black molestiae',
                'class' => 'info',
                'rfid' => '221424bb218c85bf0506564d714e71a6',
                'unit_count' => 54,
                'unit_type' => 'gr',
                'user_id' => 8,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'lime dignissimos',
                'class' => 'info',
                'rfid' => 'f77de8a203cdbcef5470a2bd6a49577e',
                'unit_count' => 6,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'aqua dolorem',
                'class' => 'info',
                'rfid' => 'e4062b704a5d815ff68212a439f540d7',
                'unit_count' => 52,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'lime et',
                'class' => 'info',
                'rfid' => 'b27aaa2cc7e6ecbf765d891cc84b8aaa',
                'unit_count' => 19,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'olive voluptatem',
                'class' => 'info',
                'rfid' => '65bc4303adec2861853fa4981fb71098',
                'unit_count' => 20,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 4,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'navy itaque',
                'class' => 'info',
                'rfid' => 'ce1b0ab2261f9370224068f2bf9158a3',
                'unit_count' => 71,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'yellow distinctio',
                'class' => 'info',
                'rfid' => 'b1bd8356f50d5c73dd8e689d8b36ccc9',
                'unit_count' => 14,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'lime illum',
                'class' => 'info',
                'rfid' => '56d2cacc240b0376162651a168f07bed',
                'unit_count' => 64,
                'unit_type' => 'gr',
                'user_id' => 9,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'navy iusto',
                'class' => 'info',
                'rfid' => '760ee2ac4e6cc131311fea9ca9f41413',
                'unit_count' => 67,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'navy maiores',
                'class' => 'info',
                'rfid' => '78089199e27cc5ab49f26db216ded57c',
                'unit_count' => 61,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'navy tempore',
                'class' => 'info',
                'rfid' => 'f6d6c6cbbbfb802863e7853d6e994ebb',
                'unit_count' => 42,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'fuchsia excepturi',
                'class' => 'info',
                'rfid' => '6020eff4c0b97f8e5c73634a0331ba03',
                'unit_count' => 74,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'black aut',
                'class' => 'info',
                'rfid' => '0a8244a13b4aea78e1960b7708f54355',
                'unit_count' => 22,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'navy impedit',
                'class' => 'info',
                'rfid' => '5684521f49f54d0de818ea724c310257',
                'unit_count' => 99,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'purple cumque',
                'class' => 'info',
                'rfid' => '72279f60b8dc0b8527d0ce3214af5bcb',
                'unit_count' => 71,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'gray explicabo',
                'class' => 'info',
                'rfid' => 'e1f097027a31e7c037a9f253aac294a4',
                'unit_count' => 5,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'purple officiis',
                'class' => 'info',
                'rfid' => '128b7ca61b5c784fd66970c1f9735ff1',
                'unit_count' => 33,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'gray quae',
                'class' => 'info',
                'rfid' => '6ddc22d071b91c25be653abe7b872a1b',
                'unit_count' => 27,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 10,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'teal quam',
                'class' => 'info',
                'rfid' => '77506022343caa7103249a7b8cbfc1d3',
                'unit_count' => 18,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'teal odio',
                'class' => 'info',
                'rfid' => 'd7508871897426cbbe0ad53a89e2c3d1',
                'unit_count' => 98,
                'unit_type' => 'gr',
                'user_id' => 3,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'fuchsia excepturi',
                'class' => 'info',
                'rfid' => '3e0abdd9ec9b6856ca5cf43e694815d6',
                'unit_count' => 41,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'yellow expedita',
                'class' => 'info',
                'rfid' => '42f7fcb6dc6da78c41d3d0f7fb7744bc',
                'unit_count' => 54,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'teal fugit',
                'class' => 'info',
                'rfid' => 'f21babc877873e72a8eeab5d4639dc91',
                'unit_count' => 1,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 7,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'fuchsia eligendi',
                'class' => 'info',
                'rfid' => '146ebcb315bef4b96c4393274b5cfd86',
                'unit_count' => 2,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 1,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'green est',
                'class' => 'info',
                'rfid' => 'a8f697bd7288835554052366b128251a',
                'unit_count' => 27,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 6,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'gray id',
                'class' => 'info',
                'rfid' => 'ee7291a9a4acaab741cbf812e9700c1b',
                'unit_count' => 13,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'olive perspiciatis',
                'class' => 'info',
                'rfid' => 'eb8bbc3bc11074e0acfaa2db3bdc1d68',
                'unit_count' => 57,
                'unit_type' => 'gr',
                'user_id' => 7,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'silver aut',
                'class' => 'info',
                'rfid' => 'b2f33ed81a3bf5f8590f02816182a6c6',
                'unit_count' => 69,
                'unit_type' => 'gr',
                'user_id' => 10,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'blue amet',
                'class' => 'info',
                'rfid' => '93fd791479b368bc8a4abc54d2b4f97a',
                'unit_count' => 62,
                'unit_type' => 'gr',
                'user_id' => 2,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'lime dolores',
                'class' => 'info',
                'rfid' => '29f9d2e90eae5e52e2645269a19bcba0',
                'unit_count' => 87,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'gray voluptate',
                'class' => 'info',
                'rfid' => '8822ed83e88e58e0c4f4361fb26e6147',
                'unit_count' => 16,
                'unit_type' => 'gr',
                'user_id' => 6,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'maroon saepe',
                'class' => 'info',
                'rfid' => '22660bd4a68b2b291ae0142c66913deb',
                'unit_count' => 5,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 3,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'aqua doloribus',
                'class' => 'info',
                'rfid' => '4fee870f1ee54b12e9729a026cb47f28',
                'unit_count' => 57,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'aqua aspernatur',
                'class' => 'info',
                'rfid' => '62e5f2aad690ace962982fac29406d0f',
                'unit_count' => 25,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 5,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'navy rem',
                'class' => 'info',
                'rfid' => '50be81187fcef77a3496df58a5204a8d',
                'unit_count' => 26,
                'unit_type' => 'gr',
                'user_id' => 4,
                'facility_id' => 8,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'black eos',
                'class' => 'info',
                'rfid' => '7f070df15572c30a0b2dd55f09272baf',
                'unit_count' => 81,
                'unit_type' => 'gr',
                'user_id' => 5,
                'facility_id' => 2,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'silver quibusdam',
                'class' => 'info',
                'rfid' => '070abbdd58401f6fd0d42024794d2011',
                'unit_count' => 60,
                'unit_type' => 'gr',
                'user_id' => 1,
                'facility_id' => 9,
                'conversation_id' => 0,
                'project_id' => 0,
                'history' => 0,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:39',
                'updated_at' => '2016-04-17 19:32:39',
            ),
        ));
        
        
    }
}
