<?php

use Illuminate\Database\Seeder;

class ProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('profiles')->delete();
        
        \DB::table('profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'first_name' => 'Nathan',
                'last_name' => 'leite',
                'profile_picture' => 'http://lorempixel.com/800/600/fashion/',
                'phone' => 2147483647,
                'address_street' => '1234 some st.',
                'address_city' => 'Denver',
                'address_state' => 'Co.',
                'address_zip' => 80223,
                'dob' => 12241979,
                'user_id' => '1',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            1 => 
            array (
                'id' => 2,
                'first_name' => 'Israel',
                'last_name' => 'Donnelly',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 0,
                'address_street' => '2061 Boyle Prairie Suite 524',
                'address_city' => 'Lake Otholand',
                'address_state' => 'Missouri',
                'address_zip' => 86481,
                'dob' => 1947,
                'user_id' => '2',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            2 => 
            array (
                'id' => 3,
                'first_name' => 'Cleo',
                'last_name' => 'Erdman',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 2147483647,
                'address_street' => '234 Schoen Curve',
                'address_city' => 'South Erika',
                'address_state' => 'Colorado',
                'address_zip' => 57161,
                'dob' => 1924,
                'user_id' => '3',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            3 => 
            array (
                'id' => 4,
                'first_name' => 'Fatima',
                'last_name' => 'Walker',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 895,
                'address_street' => '514 Block Divide Apt. 197',
                'address_city' => 'West Otto',
                'address_state' => 'Illinois',
                'address_zip' => 87728,
                'dob' => 1927,
                'user_id' => '4',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            4 => 
            array (
                'id' => 5,
                'first_name' => 'Marta',
                'last_name' => 'Hayes',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 81,
                'address_street' => '23552 Yvonne Forest Suite 084',
                'address_city' => 'Streichtown',
                'address_state' => 'South Carolina',
                'address_zip' => 34703,
                'dob' => 1921,
                'user_id' => '5',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            5 => 
            array (
                'id' => 6,
                'first_name' => 'Andre',
                'last_name' => 'Kemmer',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 2147483647,
                'address_street' => '33506 Roscoe Route',
                'address_city' => 'Wolffville',
                'address_state' => 'Delaware',
                'address_zip' => 40661,
                'dob' => 1950,
                'user_id' => '6',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            6 => 
            array (
                'id' => 7,
                'first_name' => 'Amani',
                'last_name' => 'Heaney',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 633,
                'address_street' => '7775 Charity Spurs',
                'address_city' => 'Zboncakfort',
                'address_state' => 'Utah',
                'address_zip' => 67479,
                'dob' => 1940,
                'user_id' => '7',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            7 => 
            array (
                'id' => 8,
                'first_name' => 'Viviane',
                'last_name' => 'Bruen',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 0,
                'address_street' => '81875 Schaden Island',
                'address_city' => 'Izaiahchester',
                'address_state' => 'Alabama',
                'address_zip' => 75628,
                'dob' => 1984,
                'user_id' => '8',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            8 => 
            array (
                'id' => 9,
                'first_name' => 'Casper',
                'last_name' => 'Smith',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 245219,
                'address_street' => '60175 Sauer Harbor',
                'address_city' => 'North Bellaport',
                'address_state' => 'Florida',
                'address_zip' => 16433,
                'dob' => 1923,
                'user_id' => '9',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            9 => 
            array (
                'id' => 10,
                'first_name' => 'Frank',
                'last_name' => 'Kunde',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 0,
                'address_street' => '112 Williamson Trace',
                'address_city' => 'Eladioborough',
                'address_state' => 'Michigan',
                'address_zip' => 13720,
                'dob' => 2009,
                'user_id' => '10',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            10 => 
            array (
                'id' => 11,
                'first_name' => 'Joan',
                'last_name' => 'Wyman',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 0,
                'address_street' => '72312 Daniel Divide',
                'address_city' => 'East Tomasside',
                'address_state' => 'Montana',
                'address_zip' => 43769,
                'dob' => 1964,
                'user_id' => '11',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            11 => 
            array (
                'id' => 12,
                'first_name' => 'Friedrich',
                'last_name' => 'Kautzer',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 2147483647,
                'address_street' => '8609 Toy Knolls',
                'address_city' => 'Port Marcelina',
                'address_state' => 'North Carolina',
                'address_zip' => 98694,
                'dob' => 1928,
                'user_id' => '12',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            12 => 
            array (
                'id' => 13,
                'first_name' => 'Raleigh',
                'last_name' => 'Herman',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 271,
                'address_street' => '859 Keeling Mews Apt. 897',
                'address_city' => 'Corwinborough',
                'address_state' => 'Michigan',
                'address_zip' => 71006,
                'dob' => 2008,
                'user_id' => '13',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            13 => 
            array (
                'id' => 14,
                'first_name' => 'Michale',
                'last_name' => 'Turcotte',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 0,
                'address_street' => '799 Frami Trail Apt. 207',
                'address_city' => 'North Madelynnport',
                'address_state' => 'Pennsylvania',
                'address_zip' => 15652,
                'dob' => 1920,
                'user_id' => '14',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            14 => 
            array (
                'id' => 15,
                'first_name' => 'Nicolas',
                'last_name' => 'Kreiger',
                'profile_picture' => 'http://lorempixel.com/800/600/cats/',
                'phone' => 918915,
                'address_street' => '1474 Kelley Oval Apt. 456',
                'address_city' => 'Wizaside',
                'address_state' => 'Connecticut',
                'address_zip' => 68094,
                'dob' => 1992,
                'user_id' => '15',
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
        ));
        
        
    }
}
