<?php

use Illuminate\Database\Seeder;

class TasksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tasks')->delete();
        
        \DB::table('tasks')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Et aut nostrum consequatur eius doloremque labore.',
                'description' => 'Natus cumque dolorum adipisci debitis aperiam dicta voluptate ex. Qui illum voluptas et quod. Nihil qui neque ex est hic repellat.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 5,
                'project_id' => 8,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Quo qui consequatur quaerat.',
                'description' => 'Quasi omnis excepturi sint. Autem sed eius natus qui magnam. Voluptatum animi numquam ut vel libero alias ut dolores.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Et dolores voluptatem distinctio in pariatur.',
                'description' => 'Quidem rerum nisi qui inventore. Fuga perspiciatis consequuntur ut eveniet. Quam sunt praesentium incidunt non sed.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 4,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Autem exercitationem laboriosam aspernatur optio a illum.',
                'description' => 'Est quia porro eligendi doloribus officiis maiores voluptatibus. Minus itaque laboriosam quisquam sunt officiis dolorem. Consequatur iste omnis maiores autem totam fugiat quia.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Sit reiciendis aut ratione est eos.',
                'description' => 'Consectetur molestias rerum harum. Aut vel eveniet commodi et aperiam. Delectus tempora et saepe deleniti. Fugit inventore qui velit est recusandae et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 4,
                'project_id' => 3,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Vel cumque ab ad id et sit.',
                'description' => 'Ipsum iusto ut dolores est. Sit autem qui rerum aut corporis.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 8,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Suscipit magni reprehenderit sed dicta sequi quam expedita.',
                'description' => 'Est mollitia id molestias quasi debitis. Autem aspernatur et ut debitis. Est qui reprehenderit explicabo voluptas. Neque dicta recusandae aut est.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 6,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Sunt expedita est aut ipsa velit magnam impedit.',
                'description' => 'Et facilis dolorem quibusdam. Qui omnis reprehenderit possimus sit. Asperiores earum nostrum nulla quos aperiam molestiae non. Autem rerum illo quia amet commodi nihil veritatis. Consequatur suscipit incidunt id porro aut doloribus.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Atque consequatur praesentium soluta ut eum in.',
                'description' => 'Officiis eum et et ipsa sit ea aliquid. Dolore modi perferendis quos exercitationem debitis. Amet et id sit nobis et suscipit. Reprehenderit laudantium non sit sunt.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Et laborum error est quidem suscipit architecto.',
                'description' => 'Numquam voluptatum impedit tempora cumque deleniti soluta. Eos et ullam porro aspernatur cumque architecto. Accusamus quaerat error numquam voluptate quod voluptatibus corrupti.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Inventore laboriosam et sit.',
                'description' => 'Ut ab rerum praesentium ratione repudiandae temporibus. Nihil nihil officia dolore officia unde. Iusto asperiores et asperiores quos ipsum qui. Mollitia magnam cum fugiat commodi est adipisci voluptas.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Minus sed blanditiis ut id eos eos.',
                'description' => 'Dolor impedit quam nostrum totam earum. Ut dolor repellendus est ratione sed fuga soluta. Natus molestiae fugiat repellat sit ducimus. Autem iure mollitia quia eligendi.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 9,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Et sed corporis qui.',
                'description' => 'Nulla facilis harum ut magni soluta adipisci. Id sed quo atque porro cumque magni earum. Iste suscipit quae quia perferendis cumque minima.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 8,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Officia aut omnis nulla ut sunt praesentium dolorem.',
                'description' => 'Et aut qui fuga nihil voluptatibus officia. Ea quo rerum sapiente et voluptas quidem quia. Saepe dolorum laborum expedita cumque iure cumque. Alias molestiae est consequatur esse recusandae. Nostrum et nihil voluptatem cupiditate natus.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Ut architecto dolorum odit est beatae.',
                'description' => 'Recusandae adipisci quis quasi quo aliquam aut voluptates delectus. Aut accusantium ut qui eum debitis provident. Itaque modi ut dolorem est maiores similique suscipit. Dolorem qui voluptas exercitationem perferendis illum.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 9,
                'project_id' => 2,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Placeat impedit facilis rerum unde quaerat.',
                'description' => 'Provident provident saepe ratione dolore ut numquam. Cum repudiandae aut natus occaecati ipsam veniam sed. Perferendis autem ratione sed voluptates consequatur ipsa. Tempora culpa dolor voluptas nostrum harum et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Eveniet nihil quia accusantium quod eum reiciendis enim.',
                'description' => 'Dolor possimus quia facere ipsam consequatur est corrupti. Sint fugit quasi ea minus. Id quis illo voluptates facere hic expedita et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 4,
                'project_id' => 3,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Omnis vel nulla placeat.',
                'description' => 'Adipisci maxime qui iste porro. Consequuntur animi velit provident et. Enim necessitatibus ut nemo veniam iure eligendi. Quaerat rerum debitis dolor voluptates ducimus.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Esse autem voluptatibus quis libero exercitationem nulla.',
                'description' => 'Aut harum quae voluptatibus dicta ea non. Assumenda quod expedita doloremque qui iure. Eos sed velit quis consectetur asperiores sequi.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 8,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Iusto quasi blanditiis ut et accusamus iure id.',
                'description' => 'Voluptatem illo quam quos est officiis qui. Commodi est ipsum aut non sunt eum dolore. Nesciunt voluptates quos provident quis qui placeat veritatis.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 3,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Dolore soluta ducimus delectus rerum unde ex.',
                'description' => 'Iusto rerum sed in. Illum voluptatem rerum sint libero. Blanditiis aliquid aut esse sunt rerum quia quia eaque. Iure eum vitae illum quas et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Non explicabo totam perspiciatis eligendi quo ducimus.',
                'description' => 'Qui culpa id laborum. Et possimus aut eos iste quia doloribus magni. Reprehenderit sit repudiandae ut quisquam consequatur qui. Aut et cupiditate quo similique qui quo nihil.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 9,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Nihil facilis fugit sit in sapiente veniam.',
                'description' => 'Non facere culpa soluta animi quas. Aliquid animi possimus molestiae ut libero esse ut consequuntur. Perferendis voluptatem et soluta. Aut consequuntur quas illo fugiat illum nesciunt.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Ex sed pariatur neque autem suscipit.',
                'description' => 'Molestiae qui enim repellat ratione. Nihil accusamus eos sint dignissimos saepe a. Voluptatem consequatur temporibus inventore quidem enim et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Repudiandae voluptatem aut culpa.',
                'description' => 'Quia corrupti possimus inventore voluptatem velit qui. Quidem accusantium quidem fuga omnis repellat.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'Voluptatibus autem blanditiis inventore.',
                'description' => 'Eos quidem consequuntur sint repellendus libero et. Tenetur et sit sint eos id laudantium voluptatum rerum. Iusto necessitatibus pariatur libero est. Suscipit tempore aut at aspernatur dolorem quos accusamus.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 6,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Repellat possimus accusamus reiciendis iusto.',
                'description' => 'Ut iusto dignissimos rem molestias molestiae dicta. Occaecati eum autem aut inventore debitis qui reprehenderit. Impedit velit autem nemo quia.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 5,
                'project_id' => 3,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Voluptate sit ab consequatur qui alias.',
                'description' => 'Laudantium omnis maiores distinctio temporibus dolorem. Numquam fuga incidunt molestiae commodi dolorum enim consequatur.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 2,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Itaque voluptatem in omnis incidunt explicabo provident.',
                'description' => 'Quisquam harum assumenda eveniet nam in. Eligendi occaecati doloremque quae molestiae. Facilis aut amet est delectus mollitia rerum expedita. Vel ipsam corporis aut alias et provident.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 2,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Ut quia nisi commodi commodi quisquam et placeat sunt.',
                'description' => 'Reprehenderit dolor placeat maiores sequi. Consectetur quo est aut aliquam. Repudiandae eaque quo voluptas aspernatur error velit neque expedita. Unde numquam hic reprehenderit molestiae est.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 4,
                'project_id' => 5,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Quia cumque repellendus quibusdam delectus.',
                'description' => 'Repellendus eius dolor esse vero porro. Voluptatem eveniet aut omnis voluptates sunt sunt. Suscipit dolorem in delectus mollitia est. Qui iusto est aliquam aliquid labore quisquam voluptas velit.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 8,
                'project_id' => 5,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Est voluptas temporibus eaque quasi.',
                'description' => 'Aut non qui quia. Id esse reprehenderit temporibus repudiandae rem laudantium. Molestiae unde est omnis ad enim.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 8,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Laboriosam mollitia placeat et quam aut dolores.',
                'description' => 'Non amet quia commodi sapiente. Ut accusamus cum eos dolores voluptatibus magni maiores. Dolor corrupti enim ut iste cupiditate. Saepe voluptas ipsa ab eaque ad veritatis voluptatem.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 2,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Possimus deserunt inventore ut aliquid impedit laudantium.',
                'description' => 'Natus porro a nostrum. Aut non enim omnis consequatur rerum. Earum qui fugiat consequatur accusantium libero error porro.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 9,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Hic molestiae officiis hic soluta et ad.',
                'description' => 'Eos quod voluptates minus est consequuntur nihil. Sit recusandae consequatur repudiandae est sint. Consequatur quia et facilis vero. Consequatur velit quia quod velit sed.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Praesentium enim et rerum eius nam cumque fugit.',
                'description' => 'Odio eum nesciunt sed accusantium qui aliquid. Impedit necessitatibus in dolores nobis consequatur quis. Eos culpa voluptas et ducimus natus soluta. Illo quas nisi impedit voluptas voluptatum velit natus.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 9,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Dolores qui veniam libero est ut.',
                'description' => 'Ut omnis provident ut cum neque at quo. Ex provident facilis quia officia. Mollitia libero esse quis iusto voluptatem enim accusamus quis. Enim aut ut quam ut maiores molestiae.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Amet et aut facilis quibusdam.',
                'description' => 'Error exercitationem sed expedita voluptas. Omnis blanditiis reiciendis libero. Ut dignissimos maxime atque atque eum ratione temporibus. Cum impedit atque mollitia beatae vel at.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Ut autem magni nostrum placeat aut eius quia.',
                'description' => 'Delectus facilis voluptates necessitatibus quia perferendis eos. Minima voluptas explicabo laudantium error in non quo. Et iste dolores architecto corrupti velit.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Iure quidem dignissimos voluptate et est necessitatibus dolorum.',
                'description' => 'Est ducimus consequuntur laboriosam veritatis. Natus asperiores voluptatem et recusandae velit quae sed. Delectus aspernatur recusandae enim architecto dolor non.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '02:32:44',
                'due_date' => '2016-04-20',
                'owner_id' => 1,
                'conversation_id' => 9,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-17 19:32:44',
                'updated_at' => '2016-04-17 19:32:44',
            ),
        ));
        
        
    }
}
