<?php

use Illuminate\Database\Seeder;

class TasksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tasks')->delete();
        
        \DB::table('tasks')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Quis nulla possimus ex.',
                'description' => 'Ipsum ducimus atque nostrum atque nobis. Similique molestiae doloremque sed unde pariatur amet. Aperiam similique perspiciatis quis nihil facere molestiae delectus. Non voluptates assumenda id fuga quasi est accusantium.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 6,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Velit eos in officia corporis est fugiat debitis id.',
                'description' => 'Saepe libero tempore sint corrupti. Explicabo excepturi tempora reiciendis esse. Magnam consequatur fugiat ab suscipit corrupti.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 6,
                'project_id' => 6,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Non soluta ab aliquid excepturi aut at.',
                'description' => 'Quidem inventore dicta hic ab. Id ducimus accusantium et reiciendis sequi perspiciatis sunt. Porro et ex rerum autem placeat placeat. Ipsam voluptas cum unde sit iste aut reprehenderit.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 6,
                'project_id' => 5,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Occaecati voluptatum quisquam qui id molestias ipsum.',
                'description' => 'Esse expedita eos laboriosam ex. Id itaque provident et voluptas molestiae officiis. Sunt consequatur adipisci minus reprehenderit. Voluptatem ea alias et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Dicta id voluptatem ipsa accusantium architecto nesciunt vel similique.',
                'description' => 'Aperiam sed expedita in sapiente. Quo sequi natus reprehenderit et. Autem et omnis sequi praesentium.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 6,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Dicta ipsam qui quibusdam et nostrum.',
                'description' => 'Quo quibusdam qui minima deleniti et fuga ut consectetur. Occaecati voluptatem suscipit qui dolores unde et. Ea sunt tempora ut soluta. Quo consequatur error tenetur non nisi sunt. Dolor veritatis et dolorem ex quo qui dolor in.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 9,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Veritatis totam cumque quis quo sint error.',
                'description' => 'Quas cumque illum nihil. Voluptatem sed vel consequatur et non sunt. Ut magnam enim aperiam nihil eveniet fugiat.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 2,
                'project_id' => 6,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Sunt ut nisi ut iste quam doloribus et.',
                'description' => 'Cum officiis corporis aliquam sint minus sapiente libero accusamus. Asperiores velit provident ad. Aut fuga excepturi dolorem nemo amet. Voluptatibus molestiae fugiat maxime porro culpa.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 5,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Est cum iure voluptatem animi.',
                'description' => 'Totam et tempore consequatur quia. Non qui quae ut occaecati in beatae. Nobis tenetur ipsam omnis possimus. Distinctio in blanditiis eaque quam sit nulla. Ab est excepturi fuga tempora exercitationem.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 5,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'A ad maxime et occaecati non optio tempora.',
                'description' => 'Ea fuga voluptatem occaecati itaque dolore et. Suscipit reiciendis ut totam vero et consectetur qui explicabo. In repellendus ipsum et. Est labore eligendi omnis sit ipsum aut unde qui.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 2,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Non veritatis eaque rerum voluptatem consequatur aut porro ut.',
                'description' => 'Saepe rerum sed occaecati et nesciunt reprehenderit. Fugit nesciunt adipisci occaecati molestias. Maxime consectetur autem sapiente iste temporibus ipsa voluptatum. Debitis dicta nulla omnis voluptatem qui accusantium voluptates.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 8,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Pariatur rerum eaque molestiae et praesentium cum unde.',
                'description' => 'In a facilis in iure. Corrupti magni sit fugit repudiandae. Iste quia alias ullam et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 5,
                'project_id' => 6,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Velit aspernatur eius voluptatem et nostrum sit non.',
                'description' => 'Molestiae tempore maiores nam qui sit sed perferendis. Architecto exercitationem odio ipsum tempore ex omnis. Nesciunt molestiae nam placeat aut aut.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 9,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Consectetur consequatur neque nulla velit nihil aut.',
                'description' => 'Voluptate est dolorum sunt. Error cupiditate provident incidunt qui numquam cumque enim. Officia corrupti iusto earum incidunt expedita dolores.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 8,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Voluptatem ut totam iusto quidem minus.',
                'description' => 'Neque veritatis asperiores temporibus sed libero eum. Cumque voluptatibus molestiae autem esse. Voluptatibus aperiam veritatis aut eius voluptas nihil alias. Nobis placeat dolor corporis maiores et sapiente officiis voluptate.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 2,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Eos a architecto laboriosam officia voluptas.',
                'description' => 'Corporis harum quibusdam vel omnis eum. Provident maxime et asperiores illum ab non. Voluptatem autem sapiente dicta quis in a.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Odio distinctio est cum ratione.',
                'description' => 'Molestias ut ut non quis. A voluptas et neque consectetur rerum. Error praesentium soluta non.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 6,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Nesciunt sunt nemo consequatur neque.',
                'description' => 'Aut consectetur nisi dolore repudiandae et quia quia. Vel qui ut et exercitationem blanditiis ut.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 2,
                'project_id' => 3,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Saepe dicta debitis porro non.',
                'description' => 'Tenetur ad atque saepe deserunt dolores suscipit vel. Explicabo fugiat voluptatibus quisquam voluptatum necessitatibus sunt. Aut dolor vitae itaque quis.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 2,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Quo sint eum itaque fugit rerum quaerat.',
                'description' => 'Iure quasi est exercitationem cumque est adipisci quia. Consequatur dicta aspernatur in est enim iure. Fuga nemo non repellendus hic et et eligendi. Omnis et molestiae praesentium voluptates autem commodi fuga sit.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Illo eum at dolores voluptatem aut.',
                'description' => 'Non hic sunt dicta maxime. Adipisci voluptatibus quam pariatur perspiciatis ea earum temporibus fugit. Beatae exercitationem asperiores illum tempore sunt. Consequatur quo suscipit eveniet sint neque nemo quia architecto. Id dolor asperiores nemo quia.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 8,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Cum earum officia unde quod.',
                'description' => 'Blanditiis nihil blanditiis fugit nulla sint occaecati. Voluptatibus animi odio voluptas sit dolores.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 3,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Et atque reiciendis blanditiis qui culpa dicta.',
                'description' => 'Enim totam quo incidunt aliquid vel magni perspiciatis. Expedita praesentium asperiores aut ut. Earum harum doloremque exercitationem inventore amet quidem velit facilis. Sequi commodi blanditiis reiciendis necessitatibus ea omnis recusandae id.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 8,
                'project_id' => 2,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Vel dolorum enim totam accusamus in aspernatur sed aut.',
                'description' => 'Qui dolorem aperiam aut voluptas dolorem. Et enim doloremque et culpa aut unde. Aut cumque ex sunt optio at dolor ipsa enim.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 6,
                'project_id' => 6,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Ut expedita magnam aut corrupti minima asperiores.',
                'description' => 'Quae sunt quasi accusantium optio. Quia deserunt sunt minima rerum vitae. Doloribus qui perspiciatis eius voluptates est. Quae molestiae omnis architecto ad et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'Et aut officiis est eos quod.',
                'description' => 'Magni beatae qui nisi tempore vitae. Qui quis voluptas dolores iste. Architecto odit expedita dolores eius ut nihil optio.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 8,
                'project_id' => 6,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Doloremque natus nam minima rerum assumenda.',
                'description' => 'Et est et consectetur praesentium ut. Eaque amet rerum nobis quisquam sed aperiam iure suscipit. Quos iste sed magni voluptatem dolore consequatur tenetur.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 2,
                'project_id' => 8,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Occaecati quia vitae iusto dolor eos deserunt porro delectus.',
                'description' => 'Illum pariatur animi reprehenderit numquam impedit recusandae alias. Et aut eaque enim sit enim pariatur. Mollitia aut error explicabo id beatae. Qui possimus tenetur voluptatum qui dolorem sit velit vel.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 8,
                'project_id' => 3,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Quae suscipit quidem at enim rerum rerum.',
                'description' => 'Nobis modi laboriosam ut voluptas explicabo. Eligendi ea in non et rem. Sit nostrum consequatur qui ratione.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 10,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Non assumenda vel nobis facilis officiis et.',
                'description' => 'Quasi deleniti dolorum quia voluptas quis voluptate iure in. Dolore vero expedita dolor omnis consequatur et reiciendis. Dolores repellat quo consectetur expedita deleniti eos rem iusto. Et eum dolor eius distinctio repellat nobis vel minus. Sit sequi vol',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 9,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Iure voluptatibus sint quia consectetur.',
                'description' => 'Non doloremque quod illo cum. Ab minus quibusdam vero. Nulla sint corrupti tempora ea. Et accusamus repellat perferendis dolore aut. Dolorem voluptatem deleniti et totam.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 8,
                'project_id' => 2,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Nisi dolores reiciendis voluptate et nihil occaecati.',
                'description' => 'Quidem perferendis deserunt suscipit labore. Voluptatem cupiditate reiciendis occaecati ducimus. Aut dolores libero soluta sint deleniti molestias. Harum sequi sequi est eum.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 9,
                'project_id' => 8,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Aut voluptas recusandae et enim molestias.',
                'description' => 'Et laboriosam quibusdam ea et harum repudiandae qui itaque. Delectus consequatur esse fugiat fuga molestiae id odit. Sit fugit natus dolorem modi veritatis dolor animi dolores. Dolores eligendi quas placeat nostrum.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 10,
                'project_id' => 3,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Sunt dicta at soluta libero a deserunt rerum.',
                'description' => 'Adipisci similique aperiam explicabo. Blanditiis odio molestiae cumque optio itaque id. Vel veniam id ab est placeat maxime.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 3,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Amet odit repellat aliquid consequatur dolore delectus.',
                'description' => 'Reiciendis minus qui sit earum modi. Non enim impedit sunt cumque ea animi aspernatur. Deserunt aliquam deleniti amet et molestiae. Et id deserunt tempora nobis iure veritatis.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 1,
                'project_id' => 2,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Nulla ut odit et quia dolore ipsum.',
                'description' => 'Perferendis dolorem voluptatem temporibus amet. Et cumque voluptates voluptates consequuntur sed. Voluptas occaecati neque ex voluptate molestias molestiae. Ut ducimus est veritatis ad ex est.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 9,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Tempore eius in totam sapiente.',
                'description' => 'Ea eius sint temporibus laboriosam cupiditate aspernatur. Laudantium quo ut impedit consequatur necessitatibus ad. Aperiam laudantium doloribus amet aliquam totam ullam natus. Et molestias est quo ducimus. Ad rerum inventore earum cumque in qui eum sed.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 6,
                'project_id' => 1,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Doloremque voluptas qui ad sint et ducimus consectetur.',
                'description' => 'Blanditiis molestiae consectetur non aliquam veniam laudantium. Tempora molestiae aperiam eligendi. Perferendis placeat voluptatem iste laborum et ducimus.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 2,
                'project_id' => 2,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Quia saepe nisi vitae minus inventore.',
                'description' => 'Molestias ut quasi optio earum quia amet. Explicabo ut et rerum voluptate quis sunt quae. Vel pariatur illo accusantium iure neque architecto. Non molestiae quod maxime cum doloribus sapiente quis et.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 7,
                'project_id' => 4,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Quos quasi eos quibusdam nulla quia rerum.',
                'description' => 'Dolor dolorem dolores eligendi quia maxime. Quo voluptatem illo neque temporibus fuga vero eum. Consectetur et molestiae dolore vero. Molestiae saepe ad quo omnis est.',
                'description_height' => 40,
                'class' => 'info',
                'due_time' => '13:18:59',
                'due_date' => '2016-04-28',
                'owner_id' => 1,
                'conversation_id' => 5,
                'project_id' => 7,
                'facility_id' => 1,
                'creator_id' => 1,
                'deleted' => 0,
                'deleted_at' => NULL,
                'created_at' => '2016-04-25 06:18:59',
                'updated_at' => '2016-04-25 06:18:59',
            ),
        ));
        
        
    }
}
