<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'NateTheAverage',
                'email' => 'iam@natetheaverage.com',
                'password' => '$2y$10$yGdAgtSBi6gUwA9.A4czn.pyHWZHxf5e7JcTJMHdTiYyCIUjncO1O',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 1,
                'ticketit_agent' => 1,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'GO7FUCK7URSELF',
                'created_at' => '2016-04-25 06:18:53',
                'updated_at' => '2016-04-25 06:18:53',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Doug.T',
                'email' => 'dougmt_98@yahoo.com',
                'password' => '$2y$10$q0Nv/MuRvj5YgdzcxAb.Mukd5dPV5ow0plmgK9/i0D5O6LffP7CKi',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2016-04-25 06:18:53',
                'updated_at' => '2016-04-25 06:18:53',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Brian.T',
                'email' => 'bryanthompson@itwiseus.com',
                'password' => '$2y$10$eoxnxIc0iSd1AB7ARZ1dpOUMnyyJm0cL.aTCuHh3o3PAVAM4OrsY6',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2016-04-25 06:18:53',
                'updated_at' => '2016-04-25 06:18:53',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Jett.Jones',
                'email' => 'demo3@natetheaverage.com',
                'password' => '$2y$10$.6RcW79JSrviRmN.m6i.pO8at5IaB8b7.IhRyi284W8ZAF6t9pm.6',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2016-04-25 06:18:54',
                'updated_at' => '2016-04-25 06:18:54',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'SirJude',
                'email' => 'demo4@natetheaverage.com',
                'password' => '$2y$10$UlfXo2XQY/emLyk3wR0QdeoUcEIqoabzumFB0d5GQI6yT17cB8EIi',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2016-04-25 06:18:54',
                'updated_at' => '2016-04-25 06:18:54',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Dr. Quincy Wintheiser',
                'email' => 'aAbernathy@Kirlin.com',
                'password' => '$2y$10$Uw1b2zSjAFkwU7bgU.OX5uRQJZzWp5GmgZZk.0DqWBDKKMcY49jWG',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'A8eUV5xQI1',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Myra Jenkins',
                'email' => 'Schneider.Syble@Fadel.org',
                'password' => '$2y$10$yKf4/hXyqnJBclWB.R3Ui.lxwPZ/OKUu9Sy7NJ4A2.OsJ2hpU4zUm',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'FPYmcxlB40',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Ms. Alana Mueller',
                'email' => 'Gerson01@Kilback.net',
                'password' => '$2y$10$BSyvn0n/Evdwid89E2a61OzY9Ij8F8/n9UQKZAhJ8mu25taUQkuF2',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'gzpehYISni',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Sterling Eichmann',
                'email' => 'Verla.Sporer@Smitham.com',
                'password' => '$2y$10$/GznRlrP/fPZ4tv8ngX9fe4C9i3u1SxORRjs0yPgX7MD8y.3wwu0m',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'pkNvm9CaIw',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Tania Stanton',
                'email' => 'Tiara55@Crist.com',
                'password' => '$2y$10$CZaLoxJPKEoKXmiy/hRJieD9ypO8owMhCKf6G91cXVEp6PYAgGI9y',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => '2eMmamHES6',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Mr. General Champlin MD',
                'email' => 'wHegmann@Murray.net',
                'password' => '$2y$10$fExJNixV8w4pmZMbThh/v.9/BePIN2L6lmsLrq2ozV/972Yix3u8O',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'wrLiydxR5V',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Keyshawn Stroman',
                'email' => 'Etha.Heathcote@yahoo.com',
                'password' => '$2y$10$x00CAMxkQb74Jt268RZ23ekxMeg40OJqWNIfl05jz1CA1KTnuZJSG',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'LdME4lj4iD',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Rollin Mayert',
                'email' => 'Chet.Reynolds@Hane.com',
                'password' => '$2y$10$s90Krc48BqHO414sw6nHOeNTJ0Bx9FTUl.bmqwn0iHj.GqGlRXAPW',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => '6CvdLUjkor',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Houston Conn',
                'email' => 'Patsy48@hotmail.com',
                'password' => '$2y$10$EhKbfoQ2nfOQ8WcdeCOg3ObmEnui7wLy1tZ97CWBaPBOJgfAGw0ky',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'Mu1Y19WUgJ',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Prof. Henry Dicki',
                'email' => 'Brooklyn.Metz@Goldner.com',
                'password' => '$2y$10$oXqvnxYubJuhOTO8My.JXOeGiHjsDskSPDd7AY/PMtfYVRgQC4t7m',
                'stripe_id' => NULL,
                'card_brand' => NULL,
                'card_last_four' => NULL,
                'trial_ends_at' => NULL,
                'ticketit_admin' => 0,
                'ticketit_agent' => 0,
                'preferences_id' => 0,
                'facility_id' => 0,
                'profile_id' => 0,
                'customer_id' => 0,
                'employee_id' => 0,
                'taggable_id' => 0,
                'taggable_type' => '',
                'deleted_at' => NULL,
                'remember_token' => 'mpURR3JXHT',
                'created_at' => '2016-04-25 06:18:55',
                'updated_at' => '2016-04-25 06:18:55',
            ),
        ));
        
        
    }
}
